import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  eventsConatiner: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    elevation: 4,
    borderRadius: 8,
    marginTop: 20,
    backgroundColor: '#ffffff',
  },

  eventHead: {
    color: '#3B3A3A',
    fontFamily: 'proxima-nova-semiBold',
    fontSize: 20,
    marginBottom: 10,
    fontWeight: 'bold',
  },
  eventSubHead: {
    color: '#727171',
    fontFamily: 'proxima-nova-semiBold',
    fontSize: 16,
    marginBottom: 10,
  },
  eventBox: {
    paddingHorizontal: 12,
    paddingVertical: 13,
    backgroundColor: '#C1CB99',
    borderRadius: 8,
    width: '100%',
    marginTop: 10,
    flexDirection: 'row',
  },
  eventTime: {
    color: '#616D2F',
    fontFamily: 'proxima-nova-regular',
    fontSize: 12,
    marginBottom: 2,
  },
  eventTxt: {
    color: '#3B3A3A',
    fontFamily: 'proxima-nova-regular',
    fontSize: 15,
  },
  detailsBtn: {
    backgroundColor: '#F57E4A',
    height: 30,
    width: '46%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 3,
  },
  detailsBtnTxt: {
    color: 'white',
    fontFamily: 'proxima-nova-regular',
    fontSize: 16,
  },
  rsvpBtn: {
    backgroundColor: '#3B3A3A',
    height: 30,
    width: '46%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 3,
  },
  enrollBtn: {
    backgroundColor: '#616D2F',
    height: 38,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  enrollInput: {
    borderColor: '#C1CB99',
    borderWidth: 1,
    borderRadius: 6,
    marginBottom: 20,
    marginTop: 3,
    width: '100%',
    height: 39,
    padding: 6,
    paddingLeft: 10,
    fontSize: 15,
    // fontFamily: 'poppins_light',
    fontFamily: 'proxima-nova-regular',
  },
  label: {
    textAlign: 'left',
    color: '#727171',
    fontFamily: 'proxima-nova-regular',
    fontSize: 16,
    alignSelf: 'flex-start',
  },
  button: {
    backgroundColor: '#F57E4A',
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 6,
    marginTop: 12,
    width: '100%',
    alignItems: 'center',
  },
});
