import {StyleSheet} from 'react-native';
import colors from '../../../Helpers/Colors';
import {Height, Width} from '../../../Helpers/Dimensions';
export default StyleSheet.create({
  bgImage: {
    width: '100%',
    height: '100%',
  },
  cardTxt: {
    fontFamily: 'proxima-nova-bold',
    color: '#ffffff',
    fontSize: 23,
    textAlign: 'center',
  },
  dateHead: {
    fontFamily: 'proxima-nova-bold',
    color: '#ffffff',
    fontSize: 38,
    marginVertical: 10,
    textAlign: 'center',
  },
  dateSubHead: {
    fontFamily: 'proxima-nova-light',
    color: '#ffffff',
    fontSize: 25,
    textAlign: 'center',
  },
  welcomeTxt: {
    fontFamily: 'proxima-nova-semiBold',
    color: '#3B3A3A',
    fontSize: 20,
  },
  desc: {
    fontSize: 15,
    fontFamily: 'proxima-nova-light',
    color: '#3B3A3A',
    marginTop: 8,
  },
  line: {
    borderBottomColor: '#DBDBDB',
    borderBottomWidth: 0.5,
    marginTop: 12,
  },
  welcomeContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: '100%',
    elevation: 5,
    height: 170,
    marginTop: 15,
  },
  communityContainer: {
    paddingHorizontal: 13,
    paddingVertical: 13,
    backgroundColor: 'white',
    borderRadius: 6,
    marginTop: 18,
    width: '94%',
    borderColor: '#D3AB03',
    borderWidth: 1,
  },
  communityHead: {
    fontSize: 17,
    color: '#3B3A3A',
    fontFamily: 'proxima-nova-regular',
  },
  categoryHead: {
    fontSize: 25,
    color: '#3B3A3A',
    fontFamily: 'proxima-nova-regular',
    textDecorationLine: 'underline',
    marginBottom: 3,
  },
  historyHead: {
    fontSize: 20,
    color: '#3B3A3A',
    fontFamily: 'proxima-nova-regular',
    marginBottom: 3,
  },
  communityTime: {
    color: '#767676',
    fontSize: 12,
    fontFamily: 'proxima-nova-light',
    marginTop: 5,
  },
  item: {
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderRadius: 8,
    borderColor: '#707070',
    borderWidth: 1,
    marginTop: 7,
  },
  itemTxt: {
    fontFamily: 'proxima-nova-regular',
    fontSize: 14,
    color: '#707070',
  },
  communityBold: {
    color: '#3B3A3A',
    fontSize: 18,
    fontFamily: 'proxima-nova-bold',
    marginTop: 10,
    textAlign: 'center',
  },
  bookingContainer: {
    backgroundColor: '#F57E4A',
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 6,
    marginTop: 12,
    width: '100%',
  },
  bookingTxt: {
    fontSize: 14,
    color: '#ffffff',
    lineHeight: 19,
    fontFamily: 'proxima-nova-regular',
    textAlign: 'center',
  },
  profilePic: {
    width: 50,
    height: 50,
    borderRadius: 100,
    marginRight: 10,
  },
  profilePicSmall: {
    width: 22,
    height: 22,
    borderRadius: 100,
    marginRight: 10,
  },
  underlineTxt: {
    textDecorationLine: 'underline',
    color: '#616D2F',
  },
  gallery: {
    height: 80,
    width: 80,
    backgroundColor: '#E5E5E5',
    borderRadius: 5,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addTxt: {
    fontSize: 12,
    fontFamily: 'proxima-nova-regular',
    marginTop: 8,
    color: '#3B3A3A',
    textAlign: 'center',
  },
  mindPost: {
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    marginTop: 15,
    flexDirection: 'row',
  },
  cancel: {
    backgroundColor: '#9D9D9D',
    borderRadius: 5,
    width: 100,
    height: 30,
    marginRight: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  post: {
    backgroundColor: '#F57E4A',
    borderRadius: 5,
    width: 100,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnTxt: {
    fontSize: 15,
    color: '#ffffff',
    fontFamily: 'proxima-nova-regular',
  },
  bgimage: {
    width: '100%',
    height: 209,
    borderRadius: 10,
  },
  mind: {
    color: '#9D9D9D',
    fontSize: 16,
    fontFamily: 'proxima-nova-light',
    borderBottomColor: '#DBDBDB',
    borderBottomWidth: 0.5,
    width: '90%',
  },
  mind2: {
    color: '#9D9D9D',
    fontSize: 16,
    fontFamily: 'proxima-nova-light',
    borderBottomColor: '#9F9F9F',
    borderBottomWidth: 1,
    paddingBottom: 0,
    width: '70%',
  },
  loginBtn: {
    backgroundColor: '#F57E4A',
    borderRadius: 6,
    marginTop: 30,
    width: '50%',
    height: 44,
    marginBottom: 30,
  },
  btnText: {
    textAlign: 'center',
    color: 'white',
    padding: 9,
    fontSize: 18,
    fontFamily: 'poppins_light',
  },
  orderHead: {
    textAlign: 'left',
    color: '#3B3A3A',
    fontSize: 12,
    fontFamily: 'poppins_light',
  },
  orderHead2: {
    textAlign: 'left',
    color: '#3B3A3A',
    fontSize: 13,
    fontFamily: 'poppins_medium',
  },
  orderTxt: {
    textAlign: 'left',
    color: '#3B3A3A',
    fontSize: 13,
    fontFamily: 'poppins_regular',
  },
  line: {
    borderBottomColor: '#DBDBDB',
    borderBottomWidth: 1,
    marginVertical: 10,
    width: '100%',
  },
  selectOrder: {
    backgroundColor: 'transparent',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#F57E4A',
    marginTop: 30,
    width: 110,
    height: 35,
    marginBottom: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText2: {
    textAlign: 'center',
    color: '#F57E4A',
    fontSize: 13,
    fontFamily: 'poppins_light',
  },
  timeTxt: {
    textAlign: 'center',
    color: '#F57E4A',
    fontSize: 14,
    fontFamily: 'poppins_regular',
  },
  containerStyle: {
    borderTopColor: colors.bg,
    borderBottomColor: colors.bg,
    backgroundColor: colors.bg,
  },
  inputContainerStyle: {
    borderRadius: 10,
    backgroundColor: colors.white,
    // width: Width / 1.2,
  },
  text: {
    color: colors.black,
    marginLeft: 8,
    fontWeight: 'bold',
  },
});
